name: Pipeline testing
on: push
jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
      - name: Install Depedencies
        run: npm ci
      - name: Run Unit Test
        run: npm run test-prod
      - name: Get Unit Test Logs
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.json
